/* config-vulkan.h. Generated by cmake from config-vulkan.h.cmake */

/* Define if Vulkan SDK is available */
#cmakedefine HAVE_VULKAN

/* Define if Vulkan sparse binding headers are available */
#cmakedefine VULKAN_HAS_SPARSE_PROPERTIES
