/*
 * SPDX-FileCopyrightText: 2026 Krita contributors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer InputBuffer {
    uint values[];
} inputBuffer;

layout(set = 0, binding = 1, std430) buffer OutputBuffer {
    uint checksum;
} outputBuffer;

layout(push_constant) uniform Parameters {
    uint count;
} parameters;

void main()
{
    const uint index = gl_GlobalInvocationID.x;
    if (index < parameters.count) {
        atomicAdd(outputBuffer.checksum, inputBuffer.values[index]);
    }
}
